/**
 * Mock player roster for the PlayerFinder prototype.
 *
 * 12 players covering the major identification axes so filtering feels
 * realistic. Mix of:
 *   - sex × ethnicity × age combinations
 *   - distinct skin/hair/beard colors
 *   - players WITH and WITHOUT accessory inventory
 *   - players that look similar (same sex+age+ethnicity, differing in subtle
 *     features) so the user can stress-test how the funnel narrows.
 *
 * No IDB writes; no persistent state.
 */

const ts = (daysAgo) => Date.now() - daysAgo * 24 * 60 * 60 * 1000;

export const MOCK_PLAYERS = [
  {
    playerId: 1001,
    name: 'Michael Park',
    nickname: null,
    sex: 'male',
    ageDecade: '30s',
    ethnicityTags: ['east-asian'],
    skinTone: 'light',
    hairColor: 'black',
    hairLength: 'short',
    facialHair: 'clean',
    build: 'average',
    eyewear: 'clear',
    eyewearColor: 'black',
    headwear: null,
    accessoryInventory: [
      { accessoryId: 'a1', kind: 'hat', subtype: 'cap', color: 'blue', note: 'KC Royals', firstSeenAt: ts(40), lastSeenAt: ts(2), timesSeen: 4 },
      { accessoryId: 'a2', kind: 'top', subtype: 'hoodie', color: 'gray', note: '', firstSeenAt: ts(20), lastSeenAt: ts(5), timesSeen: 2 },
    ],
    handCount: 142,
    lastSeenAt: ts(2),
  },
  {
    playerId: 1002,
    name: 'Diego Alvarez',
    nickname: 'Cowboy',
    sex: 'male',
    ageDecade: '40s',
    ethnicityTags: ['hispanic'],
    skinTone: 'tan',
    hairColor: 'dark-brown',
    hairLength: 'short',
    facialHair: 'goatee',
    beardColor: 'dark-brown',
    build: 'heavy',
    eyewear: 'sunglasses',
    eyewearColor: 'black',
    headwear: 'cowboy',
    accessoryInventory: [
      { accessoryId: 'b1', kind: 'hat', subtype: 'cowboy', color: 'brown', note: 'Stetson', firstSeenAt: ts(120), lastSeenAt: ts(1), timesSeen: 12 },
      { accessoryId: 'b2', kind: 'jewelry', subtype: 'ring', color: null, note: 'silver belt buckle', firstSeenAt: ts(100), lastSeenAt: ts(1), timesSeen: 8 },
    ],
    handCount: 480,
    lastSeenAt: ts(1),
  },
  {
    playerId: 1003,
    name: 'James OBrien',
    nickname: null,
    sex: 'male',
    ageDecade: '60s+',
    ethnicityTags: ['caucasian'],
    skinTone: 'ruddy',
    hairColor: 'gray',
    hairLength: 'medium',
    facialHair: 'full',
    beardColor: 'gray',
    build: 'heavy',
    eyewear: 'readers',
    eyewearColor: 'tortoiseshell',
    headwear: null,
    accessoryInventory: [
      { accessoryId: 'c1', kind: 'top', subtype: 'sweater', color: 'green', note: 'Notre Dame', firstSeenAt: ts(60), lastSeenAt: ts(7), timesSeen: 5 },
    ],
    handCount: 890,
    lastSeenAt: ts(7),
  },
  {
    playerId: 1004,
    name: 'Aisha Patel',
    nickname: null,
    sex: 'female',
    ageDecade: '30s',
    ethnicityTags: ['south-asian'],
    skinTone: 'medium',
    hairColor: 'black',
    hairLength: 'long',
    hairTexture: 'straight',
    facialHair: null,
    build: 'slim',
    eyewear: 'none',
    headwear: null,
    accessoryInventory: [
      { accessoryId: 'd1', kind: 'jewelry', subtype: 'earrings', color: 'gold', note: '', firstSeenAt: ts(30), lastSeenAt: ts(3), timesSeen: 3 },
    ],
    handCount: 67,
    lastSeenAt: ts(3),
  },
  {
    playerId: 1005,
    name: 'Marcus Thompson',
    nickname: 'Hammer',
    sex: 'male',
    ageDecade: '40s',
    ethnicityTags: ['black'],
    skinTone: 'brown',
    hairColor: 'black',
    hairLength: 'shaved',
    facialHair: 'full',
    beardColor: 'black',
    build: 'muscular',
    eyewear: 'none',
    headwear: null,
    accessoryInventory: [
      { accessoryId: 'e1', kind: 'top', subtype: 'polo', color: 'black', note: '', firstSeenAt: ts(15), lastSeenAt: ts(1), timesSeen: 4 },
      { accessoryId: 'e2', kind: 'jewelry', subtype: 'chain', color: 'gold', note: '', firstSeenAt: ts(50), lastSeenAt: ts(1), timesSeen: 9 },
    ],
    handCount: 320,
    lastSeenAt: ts(1),
  },
  {
    playerId: 1006,
    name: 'Hiroshi Tanaka',
    nickname: null,
    sex: 'male',
    ageDecade: '50s',
    ethnicityTags: ['east-asian'],
    skinTone: 'light',
    hairColor: 'gray',
    hairLength: 'short',
    facialHair: 'clean',
    build: 'slim',
    eyewear: 'readers',
    eyewearColor: 'silver',
    headwear: null,
    accessoryInventory: [],
    handCount: 210,
    lastSeenAt: ts(5),
  },
  {
    playerId: 1007,
    name: 'Brenda Whitfield',
    nickname: null,
    sex: 'female',
    ageDecade: '50s',
    ethnicityTags: ['caucasian'],
    skinTone: 'fair',
    hairColor: 'blonde',
    hairLength: 'medium',
    facialHair: null,
    build: 'average',
    eyewear: 'clear',
    eyewearColor: 'gold',
    headwear: 'visor',
    accessoryInventory: [
      { accessoryId: 'g1', kind: 'hat', subtype: 'visor', color: 'pink', note: 'Bellagio', firstSeenAt: ts(80), lastSeenAt: ts(4), timesSeen: 6 },
    ],
    handCount: 540,
    lastSeenAt: ts(4),
  },
  {
    playerId: 1008,
    name: 'Tyler Mitchell',
    nickname: null,
    sex: 'male',
    ageDecade: '20s',
    ethnicityTags: ['caucasian'],
    skinTone: 'light',
    hairColor: 'light-brown',
    hairLength: 'medium',
    facialHair: 'stubble',
    beardColor: 'light-brown',
    build: 'slim',
    eyewear: 'none',
    headwear: 'beanie',
    accessoryInventory: [
      { accessoryId: 'h1', kind: 'hat', subtype: 'beanie', color: 'black', note: '', firstSeenAt: ts(10), lastSeenAt: ts(1), timesSeen: 3 },
      { accessoryId: 'h2', kind: 'top', subtype: 'hoodie', color: 'navy', note: 'Yankees', firstSeenAt: ts(8), lastSeenAt: ts(1), timesSeen: 2 },
    ],
    handCount: 38,
    lastSeenAt: ts(1),
  },
  {
    playerId: 1009,
    name: 'Robert King',
    nickname: 'Bobby',
    sex: 'male',
    ageDecade: '60s+',
    ethnicityTags: ['caucasian'],
    skinTone: 'fair',
    hairColor: 'white',
    hairLength: 'short',
    facialHair: 'mustache',
    beardColor: 'white',
    build: 'heavy',
    eyewear: 'clear',
    eyewearColor: 'black',
    headwear: 'fedora',
    accessoryInventory: [
      { accessoryId: 'i1', kind: 'hat', subtype: 'fedora', color: 'gray', note: '', firstSeenAt: ts(200), lastSeenAt: ts(1), timesSeen: 25 },
    ],
    handCount: 1240,
    lastSeenAt: ts(1),
  },
  {
    playerId: 1010,
    name: 'Carlos Mendez',
    nickname: null,
    sex: 'male',
    ageDecade: '30s',
    ethnicityTags: ['hispanic'],
    skinTone: 'tan',
    hairColor: 'black',
    hairLength: 'short',
    facialHair: 'goatee',
    beardColor: 'black',
    build: 'average',
    eyewear: 'sunglasses',
    eyewearColor: 'black',
    headwear: 'cap',
    accessoryInventory: [
      { accessoryId: 'j1', kind: 'hat', subtype: 'cap', color: 'red', note: 'Cardinals', firstSeenAt: ts(70), lastSeenAt: ts(2), timesSeen: 9 },
      { accessoryId: 'j2', kind: 'top', subtype: 'jacket', color: 'black', note: 'leather', firstSeenAt: ts(40), lastSeenAt: ts(2), timesSeen: 5 },
    ],
    handCount: 215,
    lastSeenAt: ts(2),
  },
  {
    playerId: 1011,
    name: 'Naomi Brooks',
    nickname: null,
    sex: 'female',
    ageDecade: '40s',
    ethnicityTags: ['black'],
    skinTone: 'brown',
    hairColor: 'black',
    hairLength: 'medium',
    hairTexture: 'curly',
    facialHair: null,
    build: 'average',
    eyewear: 'sunglasses',
    eyewearColor: 'black',
    headwear: null,
    accessoryInventory: [
      { accessoryId: 'k1', kind: 'jewelry', subtype: 'earrings', color: 'gold', note: 'hoops', firstSeenAt: ts(30), lastSeenAt: ts(3), timesSeen: 4 },
    ],
    handCount: 92,
    lastSeenAt: ts(3),
  },
  {
    playerId: 1012,
    // Player with NO name — only physical features. Owner needs to find
    // them by accessory inventory.
    name: '',
    nickname: null,
    sex: 'male',
    ageDecade: '40s',
    ethnicityTags: ['caucasian'],
    skinTone: 'light',
    hairColor: 'brown',
    hairLength: 'short',
    facialHair: 'full',
    beardColor: 'brown',
    build: 'average',
    eyewear: 'none',
    headwear: 'cap',
    accessoryInventory: [
      { accessoryId: 'l1', kind: 'hat', subtype: 'cap', color: 'green', note: 'WSOP 2024', firstSeenAt: ts(15), lastSeenAt: ts(2), timesSeen: 3 },
    ],
    handCount: 12,
    lastSeenAt: ts(2),
  },
];
