/**
 * Generate the villain dossier HTML. Every number is READ from the measurement files —
 * nothing on the page is typed by hand, so the page cannot drift from the run that made it.
 */
import { readFileSync, writeFileSync } from 'node:fs';

/**
 * buildDossier - the CANONICAL rendering of one villain's Conduct Card.
 *
 * FOUNDER, 2026-08-19: *"The shape of the artifact seems to be changing, and the shape should
 * be canonical."* Correct. The first dossier was generated by a one-off script in a scratch
 * directory with the villain's paths hardcoded, so a second villain would have meant a second
 * script - and two scripts are two shapes the moment either is edited. One generator, a villain
 * on the command line, and the shape cannot drift between subjects.
 *
 * Every figure is READ from the measurement files at build time. Nothing on the page is typed
 * by a person, so the page cannot disagree with the run that produced it.
 *
 *   PROFILE=<profile.json> CHARTS=<range-charts.json> [EXPLAIN=<explainers.json>]  *   TITLE="..." OUT=<out.html> node scripts/villainArchetype/buildDossier.mjs
 */
const need = (k) => {
  const v = process.env[k];
  if (!v) { console.error(`buildDossier: ${k} is required`); process.exit(1); }
  return v;
};
const prof = JSON.parse(readFileSync(need('PROFILE'), 'utf8'));
const charts = JSON.parse(readFileSync(need('CHARTS'), 'utf8'));
/**
 * Per-leaf explanations written by agents that each saw ONE leaf and nothing else.
 *
 * FOUNDER, 2026-08-19: *"We deliberately had agents do the interpretation of hands before,
 * forcing an explanation for each singular hand and behavior of 'What's happening here' ... it
 * was the thing that enabled this to happen."* A frequency is not an explanation, and the
 * induction only ever produces frequencies. This section is where the mechanism lives.
 *
 * Optional so the page still builds without it, but its ABSENCE IS PRINTED rather than passed
 * over: a dossier with no explanations should look unfinished, because it is.
 */
const explainers = process.env.EXPLAIN
  ? JSON.parse(readFileSync(process.env.EXPLAIN, 'utf8')) : null;
const esc = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const pct = (x, d = 1) => (100 * x).toFixed(d);
const EN = '&#8211;';
const EM = '&#8212;';

// ── the ladder, straight from the chart specs (open-* charts) ────────────────
const opens = charts.filter((c) => c.id.startsWith('open-'))
  .map((c) => ({ id: c.id.replace('open-', ''), ...c.measured, shown: c.evidence.shownCount }))
  .sort((a, b) => b.rate - a.rate);
const maxHi = Math.max(...opens.map((o) => o.ci[1]));
const L = (x) => (x / maxHi) * 100;

const ladderRows = opens.map((o) => {
  const [lo, hi] = o.ci;
  const [seat, size] = o.id.split('@');
  return '<tr>'
    + '<th scope="row"><span class="seat">' + esc(seat) + '</span>'
    + '<span class="tsize">' + esc(size) + '-handed</span></th>'
    + '<td class="num">' + pct(o.rate) + '%</td>'
    + '<td class="num dim">' + o.k + '/' + o.n + '</td>'
    + '<td class="whisker"><div class="track">'
    + '<div class="ci" style="left:' + L(lo).toFixed(2) + '%;width:' + (L(hi) - L(lo)).toFixed(2) + '%"></div>'
    + '<div class="pt" style="left:' + L(o.rate).toFixed(2) + '%"></div>'
    + '</div><span class="ci-text num">' + pct(lo) + EN + pct(hi) + '</span></td>'
    + '</tr>';
}).join('\n');

// ── the ruleset ─────────────────────────────────────────────────────────────
const VERDICT_COPY = {
  mix: 'He genuinely mixes here. Nothing he could see separates these choices.',
  'hidden-cond': 'Something he can see DOES separate this ' + EM + ' there is just not enough of it yet.',
  'needs-cards': 'Nothing observable separates this, but the hands he showed do. Only his cards resolve it.',
};
const VERDICT_LABEL = { mix: 'a genuine mix', 'hidden-cond': 'needs more hands', 'needs-cards': 'needs his cards' };

const ruleCards = prof.rules.map((r) => {
  /**
   * A band label that never varied inside the leaf is shown with the single value it covers.
   * Four of villain 1's rules read "a steep price (36-45%)" while `price_pct` was 40 on every
   * row - fixed by the blind structure, in a spot where nobody had bet. Unannotated, the rule
   * claims a price sensitivity that could not exist.
   */
  const conds = r.conds.map((c, i) => {
    const cv = r.condValues?.[i];
    const isRange = /\(\d+\s*-\s*\d+%\)|<\s*\d+%/.test(c.value);
    return cv && cv.constant && isRange
      ? esc(c.value) + ' <span class="always">always exactly ' + esc(cv.values[0]) + '</span>'
      : esc(c.value);
  }).join(' <span class="and">and</span> ');
  const bars = r.mix.map((m) => '<div class="act">'
    + '<span class="act-name">I ' + esc(m.action) + '</span>'
    + '<div class="act-bar"><div class="act-fill" style="width:' + pct(m.rate) + '%"></div></div>'
    + '<span class="act-pct num">' + pct(m.rate, 0) + '%</span>'
    + '<span class="act-ci num dim">' + pct(m.ci[0], 0) + EN + pct(m.ci[1], 0) + '</span>'
    + '<span class="act-kn num dim">' + m.k + '/' + r.n + '</span>'
    + '</div>').join('');
  const wide = (r.ci[1] - r.ci[0]) > 0.30;
  const sep = r.separators && r.separators.length
    ? '<p class="sep">Cut it with <code>' + r.separators.map((s) => esc(s.feature)).join('</code> or <code>') + '</code>.</p>'
    : '';
  return '<article class="rule v-' + r.verdict + '">'
    + '<header><span class="n num">' + r.n + '</span>'
    + '<span class="badge b-' + r.verdict + '">' + esc(VERDICT_LABEL[r.verdict] || r.verdict) + '</span>'
    + (wide ? '<span class="badge b-thin">too thin to trust</span>' : '')
    + '</header>'
    + '<p class="cond">When ' + conds + '</p>'
    + '<div class="acts">' + bars + '</div>'
    + '<p class="verdict">' + VERDICT_COPY[r.verdict] + '</p>'
    + sep
    + '</article>';
}).join('\n');

// ── range grids ─────────────────────────────────────────────────────────────
const R = '23456789TJQKA'.split('').reverse();
const gridFor = (chart) => {
  const on = new Map(chart.cells.map((c) => [c.label, c]));
  let out = '';
  for (const hi of R) {
    for (const lo of R) {
      const iH = R.indexOf(hi); const iL = R.indexOf(lo);
      const label = iH === iL ? hi + lo : iH < iL ? hi + lo + 's' : lo + hi + 'o';
      const c = on.get(label);
      let cls = 'out';
      if (c) cls = c.contradictsOrdering ? 'refute' : c.confirmed ? 'confirm' : c.weight >= 1 ? 'in' : 'edge';
      out += '<i class="' + cls + '" title="' + label + '"></i>';
    }
  }
  return out;
};

/**
 * WHICH GRIDS TO DRAW, chosen from what this villain actually has.
 *
 * Hardcoding ids meant the page could reference a chart that did not exist for this subject -
 * and did, once `bb-free` was renamed `bb-raise` after it turned out to be charting a forced
 * action. Selection is now a property of the data: prefer spots where a shown hand CONTRADICTS
 * the assumed ordering, because those are the only cells on any grid that carry evidence about
 * composition rather than convention, then fall back to the largest samples.
 */
/**
 * EVERY range he has, drawn. An earlier version picked four "most informative" charts, which is
 * an editorial decision dressed as a layout one - the reader cannot tell a spot that was
 * uninteresting from one that was omitted. Refuted spots sort first because they carry the only
 * cells that are evidence about composition rather than convention.
 */
const PICK = [...charts]
  .sort((a, b) => (Number(b.evidence.orderingRefuted) - Number(a.evidence.orderingRefuted))
    || (b.evidence.shownCount - a.evidence.shownCount)
    || (b.measured.n - a.measured.n))
  .map((c) => c.id);
const gridBlocks = PICK.map((id) => {
  const c = charts.find((x) => x.id === id);
  const ev = c.evidence;
  const note = ev.orderingRefuted
    ? '<span class="flag">Ordering refuted.</span> He showed ' + esc(ev.outsideOrdering.join(', '))
      + ' here ' + EM + ' hands the assumed strength order puts outside this range.'
    : 'No shown hand fell outside the assumed order. That is not confirmation ' + EM + ' it is '
      + (ev.shownCount === 1 ? 'a single hand' : ev.shownCount + ' hands')
      + ' shown, failing to contradict it.';
  return '<figure class="grid-fig">'
    + '<figcaption><h4>' + esc(c.title) + '</h4>'
    + '<p class="measured"><strong class="num">' + pct(c.measured.rate) + '%</strong> of the time '
    + '<span class="dim num">(' + c.measured.k + '/' + c.measured.n + ', 95% CI '
    + pct(c.measured.ci[0]) + EN + pct(c.measured.ci[1]) + ')</span>'
    + ' ' + EM + ' about <span class="num">' + c.measured.widthCombos + '</span> of 1,326 combinations.</p></figcaption>'
    + '<div class="grid">' + gridFor(c) + '</div>'
    + '<p class="grid-note">' + note + '</p>'
    + '</figure>';
}).join('\n');

const chartTable = charts.map((c) => '<tr>'
  + '<th scope="row">' + esc(c.title) + '</th>'
  + '<td class="num">' + pct(c.measured.rate) + '%</td>'
  + '<td class="num dim">' + c.measured.k + '/' + c.measured.n + '</td>'
  + '<td class="num dim">' + pct(c.measured.ci[0]) + EN + pct(c.measured.ci[1]) + '</td>'
  + '<td class="num">' + c.evidence.shownCount + '</td>'
  + '<td>' + (c.evidence.orderingRefuted
    ? '<span class="flag">refuted by ' + esc(c.evidence.outsideOrdering.join(', ')) + '</span>'
    : '<span class="dim">holds</span>') + '</td>'
  + '</tr>').join('\n');

const gateRows = prof.gates.map((g) => '<tr>'
  + '<td class="gate-ok">' + (g.ok ? 'pass' : 'FAIL') + '</td>'
  + '<th scope="row">' + esc(g.name) + '</th>'
  + '<td class="dim">' + esc(g.detail) + '</td></tr>').join('\n');

const shownTotal = prof.rules.reduce((s, r) => s + (r.shown || []).length, 0);
const unresolvedRules = prof.rules.filter((r) => r.verdict !== 'mix');
const unresolvedN = unresolvedRules.reduce((s, r) => s + r.n, 0);
const thin = prof.rules.filter((r) => (r.ci[1] - r.ci[0]) > 0.30);

/** Table sizes he actually played, read from the card - never asserted in prose. */
/**
 * The character sketch, written by an agent from the card alone. Required, because a reader who
 * cannot say what kind of player this is after the first screen has been given a table, not a
 * dossier.
 */
const characterBlock = process.env.CHARACTER
  ? readFileSync(process.env.CHARACTER, 'utf8')
  : '<p class="missing" data-empty="character">No character summary has been written for this '
    + 'villain yet.</p>';

const tableSizeLine = prof.tableSizes
  .map((t) => `${t.seats}-handed ${(100 * t.share).toFixed(0)}%`).join(' &#183; ');
const maxSeats = Math.max(...prof.tableSizes.map((t) => t.seats));
const formatLine = maxSeats <= 6
  ? `Every one of his ${prof.hands.toLocaleString()} hands was dealt at a table of ${maxSeats} seats or fewer. Not one was nine-handed.`
  : `His hands span ${prof.tableSizes.length} table sizes, up to ${maxSeats}-handed.`;

/**
 * The per-leaf mechanisms, written by agents that each saw ONE leaf and nothing else.
 * Absence is PRINTED, not passed over - a dossier without them should look unfinished.
 */
const explainerBlock = !explainers || !explainers.length
  ? '<p class="missing" data-empty="mechanisms">No per-spot mechanisms have been written for '
    + 'this villain yet. The rules above are frequencies, and a frequency is not an explanation.</p>'
  : explainers.map((e) => '<article class="mech">'
      + '<h4>' + esc(e.spot) + ' <span class="n num">' + e.n + '</span></h4>'
      + '<p class="mech-body">' + esc(e.mechanism) + '</p>'
      + (e.evidence?.length
        ? '<ul class="ev">' + e.evidence.map((x) => '<li>' + esc(x) + '</li>').join('') + '</ul>' : '')
      + (e.ambiguity ? '<p class="amb"><strong>Not settled:</strong> ' + esc(e.ambiguity) + '</p>' : '')
      + '</article>').join('\n');

/**
 * THE FAULT REGISTER. Known defects in the instrument behind this page, ranked, each with the
 * observation that would settle it. Published WITH the numbers rather than after them, because
 * a page that reads clean while its instrument has named faults is the more misleading artifact.
 */
const FAULTS = [
  ['A capability was declared absent in prose, and was not', 'The detectability census carried <code>hand-outcome</code> as ABSENT with the reason "nothing records who won the pot or how much", and on that one untested sentence 43 of 128 behaviours were written off as unreachable and the fix was filed as a corpus-extraction project. It was true of the raw file and false of the pipeline: <code>handOutcome.mjs</code> had already shipped and the adapter was already emitting the debit side for it. Measured, it resolves 2,703 of villain 1&#8217;s 2,704 hands with a zero-sum residual of 0.0000bb. Wiring it moved the census from 60 blind to 25.', 'confirmed, fixed'],
  ['The procedure ran its own copy of the one loader', '<code>loadVillain.mjs</code> exists because the same twelve-line load was re-typed in four scripts and one copy carried a 4GB OOM. <code>profileVillain</code> &#8212; the procedure &#8212; still held its own copy, so the module governed every script except the one that matters. Two consequences: the outcome attachment landed in a function the profile never called, and every named run scanned the corpus twice, ranking players it then discarded.', 'confirmed, fixed'],
  ['Four gates passed on an empty set', 'The first outcome gates reported pass with "0 of 0 hands" while the thing they check had never run. A gate that clears a population of zero is not a gate; it is a green light with no circuit behind it. Each now requires its population to be non-empty, and a separate gate names the attachment itself. Found here only because the census scores a present-but-always-null column as absent.', 'confirmed, fixed'],
  ['`acted_before` and `to_act_after` are seat-order, not action-state', 'Both count players by where they SIT, while the legend describes who has yet to act. A small blind who checks, gets bet into, and acts again reads `acted_before = 0`. Measured: 166 decisions on villain 1 and 466 on villain 2 are "first to act" while facing a bet, and ~6.7% of rows disagree with `closes`. One root cause, two mislabelled columns.', 'confirmed'],
  ['`faced_agg_prev` fires where no aggression happened', 'The flag reads "I put money in last street", not "I faced a bet or raise" — 38 rows on villain 1 sit in limped pots, which contain no preflop raise. On flop rows it effectively encodes "am I the big blind" rather than anything about aggression.', 'confirmed'],
  ['`callers_ahead` ignores limpers', 'Zero on 385 villain-1 and 894 villain-2 rows that have limpers ahead. Limpers have called the big blind; a reader treating this as "opponents already in" sees a heads-up-shaped spot that is not one.', 'confirmed'],
  ['`off_button` is blank for both blinds', 'Distance from the button is perfectly well defined for a blind, and it is dropped — 89.6% of one villain-1 spot and 28% of a villain-2 spot. The numeric position column is null exactly where position is the whole story.', 'confirmed, by design'],
  ['A fold costing nothing sits inside a mix', 'One decision per villain folds with nothing to call. Not a choice among alternatives, so it does not belong in a distribution over choices — most likely a sit-out or disconnect.', 'confirmed, unfixed'],
  ['Preflop price is a positional proxy', '`price_pct` takes exactly two values across 1,291 first-in preflop rows (40, and 25 for the small blind) because nobody has bet. Rules reading "a steep price" are annotated on this page with the single value they actually cover.', 'confirmed, annotated'],
  ['`flush_draw` means monotone on the flop', 'It fires on monotone boards only and reads `no` on all 174 two-tone flops. That matches its legend but not what its name invites; a texture test built on it silently tests something else.', 'confirmed'],
  ['A handful of bet sizes are not survivable as poker', 'Eleven of 292 bets in one villain-2 spot exceed 1.1x pot, two of them wildly — a 66.5bb bet into 11.5bb, and a 2.5x pot overbet with king-high. No situational column distinguishes those rows. Re-derive from the raw histories before fitting any sizing model.', 'unverified'],
  ['`barrels` may over-count his own preflop raise', 'An agent inferred the counter reads "streets on which anyone was aggressive", inflating opponent pressure by one whenever he was the preflop raiser. Not yet tested.', 'unverified'],
];
const faultRows = FAULTS.map(([t, d, s]) => '<tr>'
  + '<th scope="row">' + t.replace(/`([^`]+)`/g, '<code>$1</code>') + '</th>'
  + '<td>' + d.replace(/`([^`]+)`/g, '<code>$1</code>') + '</td>'
  + '<td><span class="st st-' + s.split(',')[0] + '">' + esc(s) + '</span></td></tr>').join('\n');

/**
 * WHAT HIS RANGE CAN MAKE, per street — the section that makes every frequency readable.
 *
 * FOUNDER, 2026-08-19: *"HIS HAND STRENGTH MATTERS, and we can calculate the combinatorics for
 * it. This needs to be canonical to the artifact type."*
 *
 * A betting frequency alone cannot be read. "He bets 16%" is compatible with a nit value-betting
 * a narrow range and with a maniac bluffing half his hands, and the two demand opposite
 * responses. The distribution below closes that: it is what his range MAKES on the boards he
 * actually faced, so the frequency can be set against a ceiling. Where he bets less often than
 * he can hold top pair, he is checking value; where he bets more often than value plus draws
 * combined, the excess is bluff by arithmetic and no card needs to be shown.
 *
 * EXACT rows and ASSUMED rows are reported separately and never pooled: on the exact arm his
 * range genuinely is every hand, so those numbers are facts about the deck.
 */
const strengthRows = (() => {
  const acc = new Map();
  for (const r of prof.rules) {
    for (const s of r.strength || []) {
      const key = `${s.street}|${s.basis}`;
      if (!acc.has(key)) acc.set(key, { n: 0, value: 0, draw: 0, air: 0, bet: 0, acts: 0 });
      const a = acc.get(key);
      a.n += s.n; a.value += s.value * s.n; a.draw += s.draw * s.n; a.air += s.air * s.n;
      a.bet += s.bet; a.acts += s.n;
    }
  }
  const ORDER = { flop: 0, turn: 1, river: 2 };
  return [...acc.entries()]
    .sort((x, y) => (ORDER[x[0].split('|')[0]] ?? 9) - (ORDER[y[0].split('|')[0]] ?? 9)
      || x[0].localeCompare(y[0]))
    .map(([key, a]) => {
      const [street, basis] = key.split('|');
      const v = a.value / a.n; const d = a.draw / a.n; const air = a.air / a.n;
      const bet = a.bet / a.acts;
      const verdict = bet > v + d
        ? `<span class="flag">bets ${pct(bet - v - d)}pp more than value+draws</span>`
        : bet > v
          ? `bets ${pct(bet - v)}pp above value, covered by draws`
          : `<span class="flag">checks ${pct(v - bet)}pp of value</span>`;
      return '<tr>'
        + `<th scope="row">${esc(street)}</th>`
        + `<td><span class="st st-${basis}">${esc(basis)}</span></td>`
        + `<td class="num dim">${a.n.toLocaleString()}</td>`
        + `<td class="num">${pct(v)}%</td>`
        + `<td class="num">${pct(d)}%</td>`
        + `<td class="num dim">${pct(air)}%</td>`
        + `<td class="num">${pct(bet)}%</td>`
        + `<td>${verdict}</td>`
        + '</tr>';
    }).join('\n');
})();

const strengthBlock = strengthRows
  ? '<div class="scroll"><table class="strength"><thead><tr>'
    + '<th>Street</th><th>Basis</th><th>Decisions</th><th>Top pair+</th><th>On a draw</th>'
    + '<th>Air</th><th>He bets</th><th>Reading</th></tr></thead><tbody>'
    + strengthRows + '</tbody></table></div>'
  : '<p class="missing" data-empty="strength">No hand-strength distribution was computed for '
    + 'this villain.</p>';


/**
 * THE TERMINAL-ACTION INFERENCE - what he did NOT hold, read off the action that ended the hand.
 *
 * FOUNDER, 2026-08-19: *"villain folds when a flush draw actually hits and is facing a bet. HE
 * DOES NOT HAVE THE NUT FLUSH ... we just nailed his behavior without needing to see his cards."*
 *
 * This section exists because the layer that computes it was ALREADY RUNNING AND BEING THROWN
 * AWAY. annotate() was called on every profile run and bound to a local that nothing read, so
 * the pass was paid for and the answer discarded - the exact shape of a capability that ships
 * inert. A renderer is what stops that recurring: an unread field is invisible, and an empty
 * section on a published page is not.
 *
 * The three quantities are NEVER pooled, because they are different kinds of claim. An exclusion
 * is a fact about the fold. A prior is a read about him. The contrast assumes nothing at all.
 */
const inf = prof.inference;
const terminalBlock = !inf
  ? '<p class="missing" data-empty="terminal">This profile predates the terminal-action inference '
    + 'layer. Re-run the procedure to populate it.</p>'
  : (() => {
    const exRows = (inf.exclusions || []).map((e) => '<tr>'
      + '<th scope="row">' + esc(e.street) + '</th>'
      + '<td class="num dim">' + e.n + '</td>'
      + '<td class="num dim">' + e.exact + '</td>'
      + '<td class="num">' + pct(e.meanExcluded) + '%</td>'
      + '<td class="num">' + pct(e.meanSurviving) + '%</td>'
      + '</tr>').join('');
    const exTable = exRows
      ? '<div class="scroll"><table class="strength"><thead><tr><th>Street</th>'
        + '<th>Folds facing a bet</th><th>of which exact</th><th>Range excluded</th>'
        + '<th>Range surviving</th></tr></thead><tbody>' + exRows + '</tbody></table></div>'
      : '<p class="dim">He never folded facing a bet on a board this instrument could read.</p>';

    const prRows = Object.entries(inf.prior || {}).map(([act, v]) => '<tr>'
      + '<th scope="row">I ' + esc(act) + '</th>'
      + '<td class="num dim">' + v.n + '</td>'
      + '<td class="num">' + pct(v.value) + '%</td>'
      + '<td class="num">' + pct(v.draw) + '%</td>'
      + '<td class="num">' + pct(v.air) + '%</td>'
      + '</tr>').join('');
    const prTable = prRows
      ? '<div class="scroll"><table class="strength"><thead><tr><th>When he</th>'
        + '<th>Hands shown</th><th>Top pair+</th><th>On a draw</th><th>Air</th>'
        + '</tr></thead><tbody>' + prRows + '</tbody></table></div>'
      : '<p class="dim">No action of his cleared the showdown floor, so no prior is stated at '
        + 'all. Stated properly, or not stated.</p>';

    const c = inf.contrast || {};
    const cRow = (label, v) => (v ? '<tr>'
      + '<th scope="row">' + label + '</th>'
      + '<td class="num dim">' + v.n + '</td>'
      + '<td class="num">' + pct(v.aggression) + '%</td>'
      + '<td class="num dim">' + (v.aggressionCI
        ? pct(v.aggressionCI[0], 0) + EN + pct(v.aggressionCI[1], 0) : '') + '</td>'
      + '<td class="num">' + pct(v.passive) + '%</td>'
      + '<td class="num">' + pct(v.fold) + '%</td>'
      + '</tr>' : '');
    const cRows = cRow('The draw got there', c.completed) + cRow('The draw bricked', c.missed);
    const swing = (c.completed && c.missed)
      ? (() => {
        const d = c.missed.aggression - c.completed.aggression;
        const a = c.completed.aggressionCI; const b = c.missed.aggressionCI;
        // Overlapping intervals mean the gap is not separated at this sample. Say so, in the
        // sentence, rather than quoting the point estimate as though it were the finding.
        const separated = a && b && (b[0] > a[1] || a[0] > b[1]);
        const direction = d > 0 ? 'bricks' : 'gets there';
        return '<p>' + (Math.abs(d) < 0.02
          ? 'He does not measurably change gear on the card that resolves the draw.'
          : separated
            ? 'He is <strong>' + pct(Math.abs(d)) + ' points ' + (d > 0 ? 'more' : 'less')
              + '</strong> aggressive when the draw <strong>' + direction + '</strong> than when '
              + 'it does not, and the two intervals do not overlap. No range model and no shown '
              + 'card was needed for that ' + EM + ' it is two frequencies split on an event that '
              + 'happened on the table.'
            : 'The point estimates differ by ' + pct(Math.abs(d)) + ' points in the direction of '
              + 'more aggression when the draw <strong>' + direction + '</strong>, but the two '
              + 'intervals OVERLAP, so this sample does not separate them. It is a direction to '
              + 'test on more hands, not a measured difference, and it is reported here rather '
              + 'than quoted as a finding.') + '</p>';
      })()
      : '<p class="dim">One side of the contrast is empty, so no comparison is stated.</p>';
    const cTable = cRows
      ? '<div class="scroll"><table class="strength"><thead><tr><th>On the card that resolved it</th>'
        + '<th>Decisions</th><th>He bets or raises</th><th>95% interval</th>'
        + '<th>He calls or checks</th><th>He folds</th>'
        + '</tr></thead><tbody>' + cRows + '</tbody></table></div>' + swing
      : '<p class="dim">No decision in the record followed a street where a draw was live.</p>';

    return '<h3>What a fold proves</h3>'
      + '<p>He folded facing a bet on <strong class="num">' + inf.excludedDecisions + '</strong> '
      + 'decisions. Nobody folds the effective nuts to a single bet, so those combinations leave '
      + 'his range at that node ' + EM + ' not probably, enumerably. And the exclusion compounds: '
      + 'one made on the turn still binds on the river.</p>'
      + exTable
      + '<h3>What a bet of his implies</h3>'
      + '<p>Soft, and labelled soft. His own showdowns say what an action of his has meant, and '
      + 'the count that rests on is carried with it so you can discount it. Applied to '
      + '<strong class="num">' + inf.impliedDecisions + '</strong> of his bets and raises.</p>'
      + prTable
      + '<h3>The contrast that assumes nothing</h3>'
      + cTable;
  })();

/**
 * THE DETECTABILITY CENSUS - what this instrument is blind to, independent of the villain.
 *
 * The only question on this page whose answer does not depend on the subject at all, and the
 * one that decides how everything else here should be read. A dossier reporting no timing tell,
 * no tilt and no opponent-specific adjustment describes a stable, unexploitable player - and
 * reads IDENTICALLY when the record simply has no timestamps, no session marks and no opponent
 * ids. Those are opposite in meaning and indistinguishable on a page that omits this section.
 */
const det = prof.detectability;
const detectabilityBlock = !det
  ? '<p class="missing" data-empty="detectability">This profile predates the detectability '
    + 'census. Re-run the procedure to populate it.</p>'
  : (() => {
    const share = (k) => pct(det.counts[k] / det.total, 0);
    const bar = '<div class="census">'
      + '<div class="cs cs-detectable" style="width:' + share('detectable') + '%"><span>'
      + det.counts.detectable + ' detectable</span></div>'
      + '<div class="cs cs-partial" style="width:' + share('partial') + '%"><span>'
      + det.counts.partial + ' partial</span></div>'
      + '<div class="cs cs-blind" style="width:' + share('blind') + '%"><span>'
      + det.counts.blind + ' BLIND</span></div>'
      + '</div>';
    const costRows = (det.cost || []).map((c) => '<tr>'
      + '<th scope="row"><code>' + esc(c.capability) + '</code></th>'
      + '<td class="num">' + c.behaviours + '</td>'
      + '<td>' + esc(c.why) + '</td>'
      + '<td class="dim">' + esc((c.examples || []).slice(0, 2).join('; ')) + '</td>'
      + '</tr>').join('');
    const caps = (det.capabilities || []).map((c) => '<li class="'
      + (c.present ? 'cap-have' : 'cap-miss') + '"><code>' + esc(c.name) + '</code>'
      + (c.present ? '' : ' <span class="dim">' + esc(c.why || '') + '</span>') + '</li>').join('');
    const top = (det.cost || [])[0];
    return '<p>Of <strong class="num">' + det.total + '</strong> enumerated behaviours a villain '
      + 'could have, this instrument could have FOUND <strong>' + share('detectable') + '%</strong>. '
      + '<strong>' + share('blind') + '%</strong> could not have been found even if he did them '
      + 'every hand. So a zero on this page is three different facts ' + EM + ' observed-zero, '
      + 'unexamined, or dropped ' + EM + ' and this section refuses to collapse them.</p>'
      + bar
      + (top ? '<p class="flag">The largest single cause is <code>' + esc(top.capability) + '</code>, '
        + 'which accounts for ' + top.behaviours + ' of the ' + det.counts.blind + ' blind '
        + 'behaviours. Its absence is a property of the record, not of him.</p>' : '')
      + '<div class="scroll"><table class="faults"><thead><tr><th>Missing capability</th>'
      + '<th>Behaviours lost</th><th>Why</th><th>For example</th></tr></thead><tbody>'
      + costRows + '</tbody></table></div>'
      + '<h3>What the record does and does not carry</h3>'
      + '<ul class="caps">' + caps + '</ul>';
  })();

const subs = {
  HANDS: prof.hands.toLocaleString(),
  DECISIONS: prof.decisions.toLocaleString(),
  RULES: String(prof.rules.length),
  ACCURACY: pct(prof.accuracy),
  // Read, not asserted. The template said a flat "100%" and "eighteen statements" while the
  // page beside it reported 25 rules - a number the page itself contradicted.
  COVERAGE: pct(prof.coverage),
  CARDPCT: pct(shownTotal / prof.decisions),
  BLINDPCT: pct(1 - shownTotal / prof.decisions),
  SHOWNTOTAL: String(shownTotal),
  LADDER: ladderRows,
  RULECARDS: ruleCards,
  GRIDS: gridBlocks,
  CHARTTABLE: chartTable,
  GATES: gateRows,
  GATECOUNT: String(prof.gates.length),
  UNRESN: unresolvedN.toLocaleString(),
  UNRESCOUNT: String(unresolvedRules.length),
  THINCOUNT: String(thin.length),
  // Written from the count rather than around it: a hardcoded "1 rule is too thin" became
  // "0 rule is too thin ... its interval is wider than 30 points" the moment the all-in fix
  // tightened the last one. A page that states a number it also contradicts is worse than one
  // that omits the section.
  /**
   * Written FROM the counts. The template used to state "Two rules are unresolved" and then
   * describe one of each kind; when the correction to the card test removed the needs-cards
   * verdict entirely, the page would have gone on describing a rule it no longer contained.
   */
  UNRESBLOCK: (() => {
    const hidden = unresolvedRules.filter((r) => r.verdict === 'hidden-cond');
    const cards = unresolvedRules.filter((r) => r.verdict === 'needs-cards');
    const k = unresolvedRules.length;
    if (!k) {
      return '<h3>Every rule resolved</h3><p>No rule came back needing more hands or needing his cards. That is a statement about this ruleset, not a claim that nothing is hidden &#8212; the search that produced it is described under the instrument checks.</p>';
    }
    const head = '<h3>' + (k === 1 ? 'One rule is unresolved' : k + ' rules are unresolved')
      + ' &#8212; ' + unresolvedN.toLocaleString() + ' decisions</h3>';
    const parts = [];
    if (hidden.length) {
      parts.push('<p>' + (hidden.length === 1 ? 'One is' : hidden.length + ' are')
        + ' marked <strong>needs more hands</strong>: something he can see genuinely separates his choices, and every way of cutting it lands below the sample floor. That is a sampling limit, and more of his hands would close it.</p>');
    }
    if (cards.length) {
      parts.push('<p>' + (cards.length === 1 ? 'One is' : cards.length + ' are')
        + ' marked <strong>needs his cards</strong>: nothing observable separated the choices while the hands he happened to show did. Read that verdict carefully. It is the one conclusion on this page that says more corpus cannot help, and until this run it was reached by a test held to a threshold dozens of times easier than the observable features it was competing against. Both sides are now corrected together, and analysts given these leaves blind found visible separators in two of the spots that previously carried it.</p>');
    }
    return head + parts.join('');
  })(),
  THINBLOCK: thin.length === 0
    ? '<h3>No rule is too thin to trust</h3>'
      + '<p>Every one of the ' + prof.rules.length + ' rules has a 95% interval narrower than 30 '
      + 'percentage points on each of its actions. That is a statement about precision, not about '
      + 'correctness &#8212; a narrow interval around a rule fitted to his own data is still in-sample.</p>'
    : '<h3>' + thin.length + (thin.length === 1 ? ' rule is' : ' rules are') + ' too thin to trust</h3>'
      + '<p>' + (thin.length === 1 ? 'Its confidence interval is' : 'Their confidence intervals are')
      + ' wider than 30 percentage points. '
      + (thin.length === 1 ? 'It is' : 'They are') + ' in the ruleset because '
      + (thin.length === 1 ? 'it describes' : 'they describe') + ' real decisions, and '
      + (thin.length === 1 ? 'it is' : 'they are') + ' flagged because you should not act on '
      + (thin.length === 1 ? 'it' : 'them') + '.</p>',
  REFUTED: String(charts.filter((c) => c.evidence.orderingRefuted).length),
  CHARTCOUNT: String(charts.length),
  PID: prof.pid,
  TITLE: process.env.TITLE || 'What is in this player&#8217;s head',
  TABLESIZES: tableSizeLine,
  EXPLAINERS: explainerBlock,
  FORMATLINE: formatLine,
  FAULTS: faultRows,
  CHARACTER: characterBlock,
  STRENGTH: strengthBlock,
  TERMINAL: terminalBlock,
  DETECTABILITY: detectabilityBlock,
  /**
   * PROVENANCE, READ rather than typed. The footer used to name a hardcoded profile path and
   * "schema v9" while the runs producing the page were on v12 - a page whose own account of
   * where it came from was wrong by three schema versions. Every other figure here is read
   * from the record; there was no reason this one was not.
   */
  PROFILEPATH: esc(process.env.PROFILE),
  CHARTPATH: esc(process.env.CHARTS),
  SCHEMA: String(prof.schema),
  CORPUSFILES: String(prof.sourcePaths ? prof.sourcePaths.length : 0),
};

/**
 * The publisher owns <head>, so the page cannot declare its own charset, and a host that serves
 * it without one decoded every em dash as "a-<euro>". Numeric entities are charset-independent,
 * so encode anything above ASCII. Inside <style> entities are NOT decoded (CSS has no entity
 * parser), so the box-drawing in those comments is flattened to ASCII instead.
 */
// Built from escapes, never literal characters: a literal high range in this source is
// exactly the hazard this function exists to defend against.
const nonAscii = () => new RegExp('[^\u0000-\u007F]', 'g');
const asciiCss = (css) => css.replace(nonAscii(), '-');
const entities = (s) => s.replace(nonAscii(), (ch) => '&#' + ch.codePointAt(0) + ';');
const encodePage = (page) => {
  const i = page.indexOf('<style>');
  const j = page.indexOf('</style>');
  return entities(page.slice(0, i)) + '<style>' + asciiCss(page.slice(i + 7, j))
    + '</style>' + entities(page.slice(j + 8));
};

/**
 * THE DOSSIER SHAPE, DECLARED — not a habit, and not whatever the template happens to contain.
 *
 * FOUNDER, 2026-08-19: *"This should be a DEFINED SHAPE ... this needs to almost be a schema in
 * its characteristics. You adding things once I ask to see it is not a good sign."*
 *
 * Correct, and the tell was that asking to SEE the artifact sent me writing a new capture
 * script. That only happens when the shape is implicit. A template with placeholders constrains
 * nothing: a section can be added, dropped, or silently rendered empty and every build still
 * succeeds, so two villains' dossiers can differ in what they even ATTEMPT to say.
 *
 * So the section list is a schema with a version, and the build VALIDATES against it rather
 * than trusting it:
 *   - every REQUIRED section must be present and carry real content
 *   - a section present but not declared FAILS the build - that is the ad-hoc addition this
 *     exists to stop, and a warning would not have stopped it
 *   - an optional section that is empty must say so on the page, never render blank
 *
 * Changing the shape means editing this list and bumping the version, which is a deliberate act
 * that shows up in a diff. That is the whole point.
 */
const DOSSIER_SHAPE_VERSION = 4;
const SECTIONS = [
  { id: 'masthead', required: true, minChars: 400, holds: 'who he is, and the caveat that binds every number below' },
  { id: 'vitals', required: true, minChars: 120, holds: 'hands, decisions, rules, accuracy, cards seen' },
  { id: 'character', required: true, minChars: 500, holds: 'what kind of player this is, in plain language, before any table' },
  { id: 'scoring', required: true, minChars: 400, holds: 'why coverage is not evidence and rule count is' },
  { id: 'ruleset', required: true, minChars: 800, holds: 'every rule in the first person, with intervals' },
  { id: 'strength', required: true, minChars: 300, holds: 'what his range can MAKE per street - the ceiling that makes a frequency readable' },
  { id: 'unresolved', required: true, minChars: 400, holds: 'what the ruleset fails to explain, as content not footnote' },
  { id: 'ladder', required: true, minChars: 400, holds: 'opening frequency by seat and table size, with intervals' },
  { id: 'ranges', required: true, minChars: 800, holds: 'EVERY preflop entry range he has, drawn - not a selection' },
  { id: 'mechanisms', required: true, minChars: 200, holds: 'WHY he does it, per spot, written without sight of the ruleset' },
  { id: 'faults', required: true, minChars: 400, holds: 'known defects in the instrument behind the page' },
  { id: 'blindness', required: true, minChars: 300, holds: 'what we cannot see, and why the shown hands are not a sample' },
  { id: 'terminal', required: true, minChars: 500, holds: 'what a fold PROVES, what a bet implies, and the draw contrast - the channel that works on every hand rather than the 7-9% that show down' },
  { id: 'detectability', required: true, minChars: 500, holds: 'the census of behaviours this instrument could not have found even if he had them' },
  { id: 'gates', required: true, minChars: 300, holds: 'the known-answer checks the run had to pass' },
  { id: 'provenance', required: true, minChars: 100, holds: 'the files and command this page was built from' },
];

/**
 * NOTHING UNEXPLAINED MAY SHIP.
 *
 * FOUNDER, 2026-08-19: *"if you can't explain something, dump the context into a new agent and
 * force it to explain it. This worked in a majority of cases with villain 1, and needs to be
 * part of the protocol for this artifact."*
 *
 * A protocol I am supposed to remember is not a control - the same reason every gate in this
 * directory exists. So the requirement is structural: a rule the induction could NOT resolve
 * (`hidden-cond`, `needs-cards`) or could not measure precisely (interval wider than 30 points)
 * must carry an explanation written by an agent that was handed that leaf and told to explain
 * it. If it does not, the build refuses.
 *
 * The point is not that the agent always succeeds. It is that the failure to explain becomes
 * VISIBLE and ATTRIBUTED - "an analyst looked at this and could not separate it" is a finding,
 * while a silently unexplained leaf reads as though nobody tried.
 */
const unexplainedItems = (profile) => profile.rules
  .map((r) => ({
    key: r.conds.map((c) => c.value).join(' AND ') || 'everything else',
    n: r.n,
    why: r.verdict && r.verdict !== 'mix' && r.verdict !== 'always' ? r.verdict
      : (r.ci[1] - r.ci[0]) > 0.30 ? 'too-thin' : null,
  }))
  .filter((x) => x.why);

const validateCoverage = (profile, explains) => {
  const need = unexplainedItems(profile);
  const covered = new Set((explains || []).flatMap((e) => e.covers || []));
  return need
    .filter((x) => !covered.has(x.key))
    .map((x) => `no dispatched explanation for the ${x.why} rule (n=${x.n}): "${x.key}". `
      + 'Dump that leaf to an agent and add its answer under `covers`, or the dossier ships '
      + 'with a spot nobody tried to explain.');
};

const validateShape = (page) => {
  const present = [...page.matchAll(/data-section="([a-z]+)"/g)].map((m) => m[1]);
  const declared = new Set(SECTIONS.map((x) => x.id));
  const problems = [];

  for (const id of present) {
    if (!declared.has(id)) {
      problems.push(`section "${id}" is on the page but not in SECTIONS. Declare it and bump `
        + 'DOSSIER_SHAPE_VERSION, or remove it. An undeclared section is exactly the ad-hoc '
        + 'addition this check exists to stop.');
    }
  }
  for (const spec of SECTIONS) {
    const i = page.indexOf(`data-section="${spec.id}"`);
    if (i < 0) {
      if (spec.required) problems.push(`required section "${spec.id}" is missing (${spec.holds})`);
      continue;
    }
    // Content between this marker and the next section marker, tags stripped.
    const rest = page.slice(i);
    const next = rest.slice(1).search(/data-section="/);
    const body = (next < 0 ? rest : rest.slice(0, next + 1)).replace(/<[^>]*>/g, ' ').trim();
    if (body.length < spec.minChars) {
      problems.push(`section "${spec.id}" rendered ${body.length} chars, below its ${spec.minChars} `
        + `floor (${spec.holds}). An empty section must say it is empty, never render blank.`);
    }
  }
  /**
   * PRESENT IS NOT COMPLETE. A required section can render a truthful "nothing here yet" notice,
   * clear the character floor, and be counted as validated - so the build would report twelve
   * sections and the reader would meet an empty one. That is a partial that looks complete,
   * which is worse than a gap that is named.
   *
   * So a section that declares itself empty is reported separately and FAILS the build unless
   * the caller explicitly allows it. Shipping an incomplete dossier stays possible and becomes
   * a deliberate, visible act rather than a default.
   */
  const empty = [...page.matchAll(/data-empty="([a-z]+)"/g)].map((m) => m[1]);
  for (const id of empty) {
    const spec = SECTIONS.find((x) => x.id === id);
    if (spec?.required && !process.env.ALLOW_INCOMPLETE) {
      problems.push(`required section "${id}" declared itself EMPTY (${spec.holds}). `
        + 'Supply it, or set ALLOW_INCOMPLETE=1 to publish a dossier that is knowingly partial.');
    }
  }
  return { problems, empty };
};

let html = readFileSync(new URL('./templates/dossier.html', import.meta.url), 'utf8');
for (const [k, v] of Object.entries(subs)) html = html.split('{{' + k + '}}').join(v);
if (/\{\{[A-Z]+\}\}/.test(html)) {
  console.error('UNSUBSTITUTED PLACEHOLDER:', html.match(/\{\{[A-Z]+\}\}/g));
  process.exit(1);
}
const { problems: shapeProblems, empty: emptySections } = validateShape(html);
const coverageProblems = process.env.ALLOW_INCOMPLETE ? [] : validateCoverage(prof, explainers);
shapeProblems.push(...coverageProblems);
if (shapeProblems.length) {
  console.error(`buildDossier: the page does not match dossier shape v${DOSSIER_SHAPE_VERSION}`);
  for (const p of shapeProblems) console.error('  - ' + p);
  process.exit(1);
}
const out = encodePage(html);
if (nonAscii().test(out)) { console.error('non-ASCII survived encoding'); process.exit(1); }
const outPath = need('OUT');
writeFileSync(outPath, out);

console.log('wrote ' + outPath + `  (shape v${DOSSIER_SHAPE_VERSION}, ${SECTIONS.length} sections`
  + `${emptySections.length ? `, ${emptySections.length} KNOWINGLY EMPTY: ${emptySections.join(', ')}` : ' complete'})`);
console.log('hands ' + prof.hands + ' decisions ' + prof.decisions + ' rules ' + prof.rules.length
  + ' shown ' + shownTotal + ' (' + pct(shownTotal / prof.decisions) + '%)');
console.log('unresolved ' + unresolvedRules.length + ' rules / ' + unresolvedN + ' decisions, thin '
  + thin.length + ', ordering refuted ' + subs.REFUTED + '/' + subs.CHARTCOUNT);
